parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"
rules:
  no-console: off
  import/extensions: off
